
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.HBox hbox3;

	private global::Gtk.VBox vbox6;

	private global::Gtk.VBox vbox4;

	private global::Gtk.Table table2;

	private global::Gtk.Label from;

	private global::Gtk.ComboBoxEntry from1;

	private global::Gtk.Label label1;

	private global::Gtk.Label label3;

	private global::Gtk.ComboBoxEntry to;

	private global::Gtk.Entry entry2;

	private global::Gtk.Button convertbttn;

	private global::Gtk.VBox vbox5;

	private global::Gtk.Label label4;

	private global::Gtk.Label converted;

	protected virtual void Build()
	{
		global::Stetic.Gui.Initialize(this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.hbox3 = new global::Gtk.HBox();
		this.hbox3.Name = "hbox3";
		this.hbox3.Spacing = 6;
		// Container child hbox3.Gtk.Box+BoxChild
		this.vbox6 = new global::Gtk.VBox();
		this.vbox6.Name = "vbox6";
		this.vbox6.Spacing = 6;
		this.hbox3.Add(this.vbox6);
		global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.vbox6]));
		w1.Position = 0;
		// Container child hbox3.Gtk.Box+BoxChild
		this.vbox4 = new global::Gtk.VBox();
		this.vbox4.Name = "vbox4";
		this.vbox4.Spacing = 6;
		// Container child vbox4.Gtk.Box+BoxChild
		this.table2 = new global::Gtk.Table(((uint)(5)), ((uint)(1)), false);
		this.table2.Name = "table2";
		this.table2.RowSpacing = ((uint)(6));
		this.table2.ColumnSpacing = ((uint)(6));
		// Container child table2.Gtk.Table+TableChild
		this.from = new global::Gtk.Label();
		this.from.Name = "from";
		this.from.LabelProp = global::Mono.Unix.Catalog.GetString("from");
		this.table2.Add(this.from);
		global::Gtk.Table.TableChild w2 = ((global::Gtk.Table.TableChild)(this.table2[this.from]));
		w2.XOptions = ((global::Gtk.AttachOptions)(4));
		w2.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table2.Gtk.Table+TableChild
		this.from1 = global::Gtk.ComboBoxEntry.NewText();
		this.from1.AppendText(global::Mono.Unix.Catalog.GetString("Rupee(India)"));
		this.from1.AppendText(global::Mono.Unix.Catalog.GetString("Rupiah(Indonesia)"));
		this.from1.AppendText(global::Mono.Unix.Catalog.GetString("Ringgit(Malaysia)"));
		this.from1.AppendText(global::Mono.Unix.Catalog.GetString("U.S Dollar(Amerika)"));
		this.from1.AppendText(global::Mono.Unix.Catalog.GetString("Singapura Dollar(Singapura)"));
		this.from1.Name = "from1";
		this.table2.Add(this.from1);
		global::Gtk.Table.TableChild w3 = ((global::Gtk.Table.TableChild)(this.table2[this.from1]));
		w3.TopAttach = ((uint)(1));
		w3.BottomAttach = ((uint)(2));
		w3.XOptions = ((global::Gtk.AttachOptions)(4));
		w3.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table2.Gtk.Table+TableChild
		this.label1 = new global::Gtk.Label();
		this.label1.Name = "label1";
		this.label1.LabelProp = global::Mono.Unix.Catalog.GetString("amount");
		this.table2.Add(this.label1);
		global::Gtk.Table.TableChild w4 = ((global::Gtk.Table.TableChild)(this.table2[this.label1]));
		w4.TopAttach = ((uint)(4));
		w4.BottomAttach = ((uint)(5));
		w4.XOptions = ((global::Gtk.AttachOptions)(4));
		w4.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table2.Gtk.Table+TableChild
		this.label3 = new global::Gtk.Label();
		this.label3.Name = "label3";
		this.label3.LabelProp = global::Mono.Unix.Catalog.GetString("to");
		this.table2.Add(this.label3);
		global::Gtk.Table.TableChild w5 = ((global::Gtk.Table.TableChild)(this.table2[this.label3]));
		w5.TopAttach = ((uint)(2));
		w5.BottomAttach = ((uint)(3));
		w5.XOptions = ((global::Gtk.AttachOptions)(4));
		w5.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table2.Gtk.Table+TableChild
		this.to = global::Gtk.ComboBoxEntry.NewText();
		this.to.AppendText(global::Mono.Unix.Catalog.GetString("Rupee(India)"));
		this.to.AppendText(global::Mono.Unix.Catalog.GetString("Rupiah(Indonesia)"));
		this.to.AppendText(global::Mono.Unix.Catalog.GetString("Ringgit(Malaysia)"));
		this.to.AppendText(global::Mono.Unix.Catalog.GetString("U.S Dollar(Amerika)"));
		this.to.AppendText(global::Mono.Unix.Catalog.GetString("Singapura Dollar(Singapura)"));
		this.to.Name = "to";
		this.table2.Add(this.to);
		global::Gtk.Table.TableChild w6 = ((global::Gtk.Table.TableChild)(this.table2[this.to]));
		w6.TopAttach = ((uint)(3));
		w6.BottomAttach = ((uint)(4));
		w6.XOptions = ((global::Gtk.AttachOptions)(4));
		w6.YOptions = ((global::Gtk.AttachOptions)(4));
		this.vbox4.Add(this.table2);
		global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.vbox4[this.table2]));
		w7.Position = 1;
		w7.Expand = false;
		w7.Fill = false;
		// Container child vbox4.Gtk.Box+BoxChild
		this.entry2 = new global::Gtk.Entry();
		this.entry2.CanFocus = true;
		this.entry2.Name = "entry2";
		this.entry2.IsEditable = true;
		this.entry2.InvisibleChar = '•';
		this.vbox4.Add(this.entry2);
		global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.vbox4[this.entry2]));
		w8.Position = 2;
		w8.Expand = false;
		w8.Fill = false;
		// Container child vbox4.Gtk.Box+BoxChild
		this.convertbttn = new global::Gtk.Button();
		this.convertbttn.CanFocus = true;
		this.convertbttn.Name = "convertbttn";
		this.convertbttn.UseUnderline = true;
		this.convertbttn.Label = global::Mono.Unix.Catalog.GetString("Convert");
		this.vbox4.Add(this.convertbttn);
		global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.vbox4[this.convertbttn]));
		w9.Position = 3;
		w9.Expand = false;
		w9.Fill = false;
		this.hbox3.Add(this.vbox4);
		global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.vbox4]));
		w10.Position = 1;
		w10.Expand = false;
		w10.Fill = false;
		// Container child hbox3.Gtk.Box+BoxChild
		this.vbox5 = new global::Gtk.VBox();
		this.vbox5.Name = "vbox5";
		this.vbox5.Spacing = 6;
		// Container child vbox5.Gtk.Box+BoxChild
		this.label4 = new global::Gtk.Label();
		this.label4.Name = "label4";
		this.label4.LabelProp = global::Mono.Unix.Catalog.GetString("Converted amount");
		this.vbox5.Add(this.label4);
		global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.vbox5[this.label4]));
		w11.Position = 1;
		w11.Expand = false;
		w11.Fill = false;
		// Container child vbox5.Gtk.Box+BoxChild
		this.converted = new global::Gtk.Label();
		this.converted.Name = "converted";
		this.vbox5.Add(this.converted);
		global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.vbox5[this.converted]));
		w12.Position = 2;
		w12.Expand = false;
		w12.Fill = false;
		this.hbox3.Add(this.vbox5);
		global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.vbox5]));
		w13.Position = 2;
		w13.Expand = false;
		w13.Fill = false;
		this.Add(this.hbox3);
		if ((this.Child != null))
		{
			this.Child.ShowAll();
		}
		this.DefaultWidth = 400;
		this.DefaultHeight = 300;
		this.Show();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler(this.OnDeleteEvent);
		this.convertbttn.Clicked += new global::System.EventHandler(this.click);
	}
}
